hl.on("hyprland.start", function()
	-- hl.exec_cmd("dbus-update-activation-environment --all")
-- 	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("noctalia")
	hl.exec_cmd("udiskie")
	-- hl.exec_cmd("systemctl --user start hyprland-session.target")
	-- hl.exec_cmd("/usr/libexec/xdg-desktop-portal &")
	-- hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
